dreaming_config:
  display_scale: 2
  memory_checkpoint: checkpoints/memory/best_memory_model
  save_path: null
  seed_file: null
  seed_frames: 4
  temperature: 1.0
  top_k: 50
  vision_checkpoint: /home/viethq/Projects/elworld/research/training/src/checkpoints/vision/best_model
general_config:
  data_path: /home/viethq/Projects/elworld/research/training/recorded/
  frame_rate: 20
  max_frame: 3900
  total_play: 5
memory_config:
  action_dim: 22
  batch_size: 64
  context_frames: 4
  embed_dim: 128
  grid_latent_dim:
  - 24
  - 32
  hidden_dim: 256
  learning_rate: 0.0008240639038179593
  num_epochs: 20
  num_res_blocks: 4
  use_qat: true
  vocab_size: 1024
vision_config:
  add_noise: true
  batch_size: 128
  commitment_cost: 0.25
  dropout_rate: 0.1
  input_channels: 3
  input_size:
  - 256
  - 192
  l1_weight: 0.8
  latent_dim: 64
  learning_rate: 0.00018638933428187984
  mse_weight: 1.0
  num_embedding: 1024
  num_epochs: 20             # Full training target
  num_hidden: 128
  res_hidden: 32
  res_layer: 4
